_wandb:
    value:
        cli_version: 0.23.1
        e:
            h6cyt88cca5m2r1iijpqadspqkobwls2:
                args:
                    - data.batch_size=4
                    - model.lr=0.0014691594285984396
                    - seed=2026
                    - training.max_epochs=20
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 7
                cpu_count_logical: 14
                disk:
                    /:
                        total: "1081101176832"
                        used: "22835388416"
                email: s194408@dtu.dk
                executable: /home/xiaopeng/miniconda3/envs/my_env/bin/python
                git:
                    commit: 36b9b44bf3bc265e31ae6db7ab5f46310a17310e
                    remote: https://github.com/SharanSivakumar/MLOps-Group-04.git
                host: DTU-5CG5081JZZ
                memory:
                    total: "8026542080"
                os: Linux-6.6.87.1-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/c/Users/xiama/Desktop/Hobby/02476_Machine_learning_operations/project/MLOPs-Group-04/src/train.py
                python: CPython 3.13.11
                root: .
                startedAt: "2026-01-21T00:18:06.648750Z"
                writerId: h6cyt88cca5m2r1iijpqadspqkobwls2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 71
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 71
                - 103
            "3":
                - 2
                - 7
                - 13
                - 14
                - 16
                - 66
            "4": 3.13.11
            "5": 0.23.1
            "6": 4.57.5
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 4
data.batch_size:
    value: 4
lr:
    value: 0.0014691594285984396
max_epochs:
    value: 20
model.lr:
    value: 0.0014691594285984396
num_classes:
    value: 3
seed:
    value: 2026
training.max_epochs:
    value: 20
